# Generated by Django 4.1.5 on 2023-05-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=254, unique=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_img', models.ImageField(upload_to='eventimage')),
                ('event_is_liked', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
