# Generated by Django 4.1.5 on 2023-05-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_event_is_liked_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='event',
        ),
    ]
