# Generated by Django 4.1.5 on 2023-05-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_post_like_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
